dependencies:
  build:
    - ruby:2.6.3
    
build_targets:
  - name: default
    commands: 
      - gem update --system=2.7.8
      - gem install bundler
      - bundle install
      - bundle exec rake
      
ci:
  builds:
    - name: tests
      build_target: default
